- src/test/java/com/rudkids/rudkids/RudkidsApplicationTests.java
> feat: @SpringBootTest comment out

- build.gradle
- src/main/java/com/rudkids/rudkids/user/domain/Email.java
- src/main/java/com/rudkids/rudkids/user/domain/Name.java
- src/main/java/com/rudkids/rudkids/user/domain/Password.java
- src/main/java/com/rudkids/rudkids/user/domain/PhoneNumber.java
- src/main/java/com/rudkids/rudkids/user/domain/RoleType.java
- src/main/java/com/rudkids/rudkids/user/domain/User.java
- src/main/java/com/rudkids/rudkids/user/exception/InvalidEmailFormatException.java
- src/main/java/com/rudkids/rudkids/user/exception/InvalidNameException.java
- src/main/java/com/rudkids/rudkids/user/exception/InvalidPasswordException.java
- src/main/java/com/rudkids/rudkids/user/exception/InvalidPhoneNumberFormatException.java
- src/main/java/com/rudkids/rudkids/util/BaseEntityId.java
- src/test/java/com/rudkids/rudkids/user/domain/EmailTest.java
- src/test/java/com/rudkids/rudkids/user/domain/NameTest.java
- src/test/java/com/rudkids/rudkids/user/domain/PasswordTest.java
- src/test/java/com/rudkids/rudkids/user/domain/PhoneNumberTest.java
- 유저 도메인 생성
- Unit Test Code 작성
> feat: user domain (#2)

- src/main/java/com/rudkids/rudkids/domain/item/domain/Item.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductMapper.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductReader.java
- src/main/java/com/rudkids/rudkids/domain/product/domain/Bio.java
- src/main/java/com/rudkids/rudkids/domain/product/domain/Product.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductService.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductServiceImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/product/ProductReaderImpl.java
- src/test/java/com/rudkids/rudkids/domain/item/service/ItemServiceTest.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceImplTest.java
> Feat/product 프로덕트 관련 기능

- src/test/java/com/rudkids/rudkids/common/fixtures/auth/AuthServiceFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/user/UserControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/user/UserServiceFixtures.java
- src/test/java/com/rudkids/rudkids/domain/user/application/UserServiceImplTest.java
> refactor: 테스트코드 리팩토링

- src/main/java/com/rudkids/rudkids/common/ResponseEntity.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductCommand.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductMapper.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductService.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductServiceImpl.java
- src/main/java/com/rudkids/rudkids/domain/user/application/UserCommand.java
- src/main/java/com/rudkids/rudkids/interfaces/product/ProductController.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductRequest.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductResponse.java
- src/test/java/com/rudkids/rudkids/common/ControllerTest.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixture.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceImplTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
> [Feat/product] Product APIs

- build.gradle
- docker-compose.yml
- src/docs/asciidoc/auth.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/user.adoc
- src/main/resources/static/docs/auth.html
- src/main/resources/static/docs/index.html
- src/main/resources/static/docs/user.html
- src/test/java/com/rudkids/rudkids/common/ControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/auth/AuthControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/user/UserControllerTest.java
> feat: Restdocs 적용하기 (#45)

- src/main/java/com/rudkids/rudkids/common/ResponseEntity.java
- src/main/java/com/rudkids/rudkids/domain/item/service/ItemService.java
- src/main/java/com/rudkids/rudkids/domain/item/service/ItemServiceImpl.java
- src/main/java/com/rudkids/rudkids/interfaces/item/ItemController.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemRequest.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemResponse.java
- src/test/java/com/rudkids/rudkids/common/ControllerTest.java
- src/test/java/com/rudkids/rudkids/common/fixtures/item/ItemControllerFixture.java
- src/test/java/com/rudkids/rudkids/domain/item/service/ItemServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/item/ItemControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
> [Feat/item] Item APIs

- src/main/java/com/rudkids/rudkids/domain/item/service/ItemService.java
- src/main/java/com/rudkids/rudkids/domain/item/service/ItemServiceImpl.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductMapper.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductService.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductServiceImpl.java
- src/main/java/com/rudkids/rudkids/interfaces/item/ItemController.java
- src/main/java/com/rudkids/rudkids/interfaces/product/ProductController.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductResponse.java
- src/test/java/com/rudkids/rudkids/common/fixtures/item/ItemControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductServiceFixtures.java
- src/test/java/com/rudkids/rudkids/domain/item/service/ItemServiceTest.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/item/ItemControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
> Feat/product 프로덕트 상세조회 (아이템 리스트 포함)

- src/docs/asciidoc/cart.adoc
- src/main/java/com/rudkids/rudkids/domain/cart/CartCommand.java
- src/main/java/com/rudkids/rudkids/domain/cart/CartItemStore.java
- src/main/java/com/rudkids/rudkids/domain/cart/service/CartService.java
- src/main/java/com/rudkids/rudkids/domain/cart/service/CartServiceImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/cart/CartItemRepository.java
- src/main/java/com/rudkids/rudkids/infrastructure/cart/CartItemStoreImpl.java
- src/main/java/com/rudkids/rudkids/interfaces/cart/CartController.java
- src/main/java/com/rudkids/rudkids/interfaces/cart/dto/CartDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/cart/dto/CartRequest.java
- src/test/java/com/rudkids/rudkids/common/fixtures/cart/CartControllerFixtures.java
- src/test/java/com/rudkids/rudkids/domain/cart/application/CartServiceImplTest.java
- src/test/java/com/rudkids/rudkids/interfaces/cart/CartControllerTest.java
> feat: 장바구니아이템 선택 삭제 구현 및 테스트코드 작성 (#59)

- src/docs/asciidoc/cart.adoc
- src/main/java/com/rudkids/rudkids/domain/cart/CartItemMapper.java
- src/main/java/com/rudkids/rudkids/domain/cart/service/CartServiceImpl.java
- src/main/java/com/rudkids/rudkids/domain/user/domain/User.java
- src/main/java/com/rudkids/rudkids/domain/user/service/UserServiceImpl.java
- src/main/java/com/rudkids/rudkids/global/error/ControllerAdvice.java
- src/main/java/com/rudkids/rudkids/global/error/dto/ErrorResponse.java
- src/main/java/com/rudkids/rudkids/interfaces/auth/AuthController.java
- src/test/java/com/rudkids/rudkids/domain/cart/application/CartServiceImplTest.java
- 장바구니아이템 리스트 조회 리팩토링
- 장바구니 Restdocs 네이밍 변경
> refactor: 장바구니아이템 리스트 조회 로직 리팩토링

- build.gradle
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/GoogleOAuthClient.java
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/dto/GoogleTokenResponse.java
final 때문에 oauth에서 idToken이 받아지지 않았습니다.
> fix: idToken 받는 response final 제거

- src/main/java/com/rudkids/rudkids/domain/product/domain/Product.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductService.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductServiceImpl.java
- src/main/java/com/rudkids/rudkids/interfaces/product/ProductController.java
- src/test/java/com/rudkids/rudkids/common/fixtures/auth/AuthControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/cart/CartControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/magazine/MagazineControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/order/OrderServiceFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductServiceFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/user/UserControllerFixtures.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/auth/AuthControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/cart/CartControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/item/ItemControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/magazine/MagazineControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/user/UserControllerTest.java
> [fix/product] 관리자 권한 요구 

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/product.adoc
- src/main/java/com/rudkids/rudkids/domain/magazine/MagazineInfo.java
- src/main/java/com/rudkids/rudkids/domain/order/service/OrderServiceImpl.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/user/exception/NotAdminOrPartnerRoleException.java
- src/main/java/com/rudkids/rudkids/interfaces/product/ProductController.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductResponse.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixtures.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
프로덕트 관련 API Rest Docs로  문서화 #73
> [Test/product] 프로덕트 관련 API 문서화

- src/test/java/com/rudkids/rudkids/domain/auth/service/AuthServiceFailTest.java
- src/test/java/com/rudkids/rudkids/domain/auth/service/AuthServiceTest.java
- src/test/java/com/rudkids/rudkids/domain/auth/service/JwtTokenProviderFailTest.java
- src/test/java/com/rudkids/rudkids/domain/auth/service/JwtTokenProviderTest.java
- src/test/java/com/rudkids/rudkids/domain/cart/service/CartServiceFailTest.java
- src/test/java/com/rudkids/rudkids/domain/cart/service/CartServiceTest.java
- src/test/java/com/rudkids/rudkids/domain/magazine/service/MagazineServiceFailTest.java
- src/test/java/com/rudkids/rudkids/domain/magazine/service/MagazineServiceImplTest.java
> refactor: 서비스 테스트코드 성공, 실패로 분리하기 (#116)

- src/main/java/com/rudkids/rudkids/domain/image/S3ImageUploader.java
- src/main/java/com/rudkids/rudkids/domain/image/service/ImageUploader.java
- src/main/java/com/rudkids/rudkids/domain/image/service/ImageUploaderImpl.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemCommand.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemInfo.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemMapper.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemStore.java
- src/main/java/com/rudkids/rudkids/domain/item/domain/Item.java
- src/main/java/com/rudkids/rudkids/domain/item/domain/ItemImage.java
- src/main/java/com/rudkids/rudkids/domain/item/service/ItemServiceImpl.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductMapper.java
- src/main/java/com/rudkids/rudkids/infrastructure/image/ImageUploaderImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/image/S3ImageUploaderImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/item/ItemStoreImpl.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemRequest.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemResponse.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductResponse.java
- src/test/java/com/rudkids/rudkids/common/fixtures/item/ItemControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/item/ItemServiceFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixtures.java
- src/test/java/com/rudkids/rudkids/domain/item/service/ItemServiceFailTest.java
- src/test/java/com/rudkids/rudkids/domain/item/service/ItemServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/item/ItemControllerFailTest.java
- src/test/java/com/rudkids/rudkids/interfaces/item/ItemControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
> feat: 아이템에 이미지 추가 (#124)

- src/docs/asciidoc/product.adoc
- src/main/java/com/rudkids/rudkids/domain/image/ImageInfo.java
- src/main/java/com/rudkids/rudkids/domain/image/service/ImageService.java
- src/main/java/com/rudkids/rudkids/domain/image/service/ImageServiceImpl.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemCommand.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemInfo.java
- src/main/java/com/rudkids/rudkids/domain/item/ItemMapper.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductMapper.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductService.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductServiceImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/item/ItemRepository.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/item/dto/ItemResponse.java
- src/main/java/com/rudkids/rudkids/interfaces/product/ProductController.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductResponse.java
- src/main/resources/application.yml
- src/test/java/com/rudkids/rudkids/common/fixtures/image/ImageControllerFixtures.java
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixtures.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/image/ImageControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerFailTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
- src/test/resources/application.yml
> fix: 프로덕트 조회 로직 페이지네이션 하기 (#154)

- src/main/java/com/rudkids/rudkids/interfaces/product/ProductController.java
> fix: paging logic 수정

- src/main/java/com/rudkids/rudkids/domain/cart/domain/Cart.java
- src/main/java/com/rudkids/rudkids/domain/order/domain/Order.java
- src/main/java/com/rudkids/rudkids/domain/payment/PaymentClient.java
- src/main/java/com/rudkids/rudkids/domain/payment/PaymentCommand.java
- src/main/java/com/rudkids/rudkids/domain/payment/exception/InvalidAmountException.java
- src/main/java/com/rudkids/rudkids/domain/payment/exception/PaymentConfirmException.java
- src/main/java/com/rudkids/rudkids/domain/payment/service/PaymentService.java
- src/main/java/com/rudkids/rudkids/domain/payment/service/PaymentServiceImpl.java
- src/main/java/com/rudkids/rudkids/global/config/PropertiesConfig.java
- src/main/java/com/rudkids/rudkids/global/config/properties/TossPaymentProperties.java
- src/main/java/com/rudkids/rudkids/infrastructure/payment/TossPaymentClient.java
- src/main/java/com/rudkids/rudkids/interfaces/order/dto/OrderRequest.java
- src/main/java/com/rudkids/rudkids/interfaces/payment/PaymentController.java
- src/main/java/com/rudkids/rudkids/interfaces/payment/dto/PaymentDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/payment/dto/PaymentRequest.java
- src/main/resources/application.yml
- src/test/java/com/rudkids/rudkids/domain/cart/service/CartServiceFailTest.java
- src/test/java/com/rudkids/rudkids/domain/order/service/OrderServiceFailTest.java
#160 
disable되어있던 AuthenticationAdminAuthority 검증 코드는 서비스쪽에서 할 필요가 없어져서 삭제시켰습니다
> feat: toss payment 구현 (#160)

- .gitignore
- src/main/java/com/rudkids/rudkids/domain/user/service/UserServiceImpl.java
- src/main/resources/logback-spring.xml
- src/main/resources/logback-variables.properties
> feat: logback 적용해서 error level은 파일로 저장 (#178)

- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/google/GoogleInformationClient.java
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/google/GoogleOAuthClientManager.java
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/google/GoogleTokenClient.java
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/kakao/KakaoInformationClient.java
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/kakao/KakaoOAuthClientManager.java
- src/main/java/com/rudkids/rudkids/infrastructure/oauth/client/kakao/KakaoTokenClient.java
- 구글 유저 정보 가져올 때 쿼리 파라미터들을 가져오는 로직을 메서드로 분리
> refactor: google oauth logic refactoring

- readme.md
- src/main/java/com/rudkids/rudkids/domain/product/ProductCommand.java
- src/main/java/com/rudkids/rudkids/domain/product/ProductInfo.java
- src/main/java/com/rudkids/rudkids/domain/product/domain/Product.java
- src/main/java/com/rudkids/rudkids/domain/product/domain/ProductBannerImage.java
- src/main/java/com/rudkids/rudkids/domain/product/service/ProductServiceImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/item/ItemFactoryImpl.java
- src/main/java/com/rudkids/rudkids/infrastructure/product/ProductFactoryImpl.java
- src/main/java/com/rudkids/rudkids/interfaces/admin/AdminController.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductDtoMapper.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductRequest.java
- src/main/java/com/rudkids/rudkids/interfaces/product/dto/ProductResponse.java
- src/main/resources/application.yml
- src/test/java/com/rudkids/rudkids/common/fixtures/product/ProductControllerFixtures.java
- src/test/java/com/rudkids/rudkids/domain/product/service/ProductServiceTest.java
- src/test/java/com/rudkids/rudkids/interfaces/admin/AdminControllerFailTest.java
- src/test/java/com/rudkids/rudkids/interfaces/admin/AdminControllerTest.java
- src/test/java/com/rudkids/rudkids/interfaces/product/ProductControllerTest.java
> fix: product banner image 추가 (#182)

- src/test/java/com/rudkids/rudkids/common/ControllerTest.java
> style: 빈칸 정리

- src/main/java/com/rudkids/rudkids/domain/cart/domain/Cart.java
> style: annotation remove

- .gitignore
- rudkids-api/build.gradle
정적파일로 화면에 띄우기 위해선 static 디렉토리 안에 있어야 함
> fix: docs 경로 수정

- rudkids-api/src/main/java/com/rudkids/api/admin/AdminController.java
- rudkids-api/src/main/java/com/rudkids/api/item/ItemController.java
- rudkids-api/src/test/java/com/rudkids/api/admin/AdminControllerTest.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/AdminControllerFixtures.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/ItemControllerFixtures.java
- rudkids-core/src/main/java/com/rudkids/core/item/domain/ItemRepository.java
- rudkids-core/src/main/java/com/rudkids/core/item/dto/ItemResponse.java
- rudkids-core/src/main/java/com/rudkids/core/item/exception/DuplicatedNameException.java
- rudkids-core/src/main/java/com/rudkids/core/item/infrastructure/ItemRepositoryImpl.java
- rudkids-core/src/main/java/com/rudkids/core/item/infrastructure/JpaItemRepository.java
- rudkids-core/src/main/java/com/rudkids/core/item/service/ItemService.java
- rudkids-core/src/main/java/com/rudkids/core/item/service/ItemServiceImpl.java
- rudkids-core/src/test/java/com/rudkids/core/item/service/ItemServiceTest.java
> feat: 아이템 검색 api 구현 (#200)

- rudkids-api/src/main/java/com/rudkids/api/item/ItemController.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/ItemControllerFixtures.java
- rudkids-api/src/test/java/com/rudkids/api/item/ItemControllerTest.java
- rudkids-core/src/main/java/com/rudkids/core/item/domain/ItemRepository.java
- rudkids-core/src/main/java/com/rudkids/core/item/infrastructure/ItemRepositoryImpl.java
- rudkids-core/src/main/java/com/rudkids/core/item/service/ItemService.java
- rudkids-core/src/main/java/com/rudkids/core/item/service/ItemServiceImpl.java
- rudkids-core/src/test/java/com/rudkids/core/item/service/ItemServiceTest.java
> fix: item video image 반환 로직 수정

- rudkids-core/src/main/java/com/rudkids/core/auth/annotation/OAuthProvider.java
- rudkids-core/src/main/java/com/rudkids/core/auth/annotation/OAuthProviderResolver.java
- rudkids-core/src/main/java/com/rudkids/core/auth/exception/OAuthNotFoundException.java
- rudkids-core/src/main/java/com/rudkids/core/auth/service/OAuthClientStrategy.java
- rudkids-core/src/main/java/com/rudkids/core/auth/service/OAuthUriStrategy.java
- rudkids-core/src/main/java/com/rudkids/core/community/service/CommunityServiceImpl.java
- rudkids-core/src/main/java/com/rudkids/core/image/infrastructure/S3ImageClientImpl.java
- rudkids-core/src/main/java/com/rudkids/core/image/service/ImageDeletedEvent.java
- rudkids-core/src/main/java/com/rudkids/core/image/service/ImageDeletedEventListener.java
- rudkids-core/src/main/java/com/rudkids/core/item/service/ItemServiceImpl.java
- rudkids-core/src/main/java/com/rudkids/core/product/service/ProductServiceImpl.java
- rudkids-core/src/main/java/com/rudkids/core/user/service/UserServiceImpl.java
> feat: event driven 적용 (#234)

- rudkids-core/src/main/resources/application-test.yml
> feat: restdocs content update

- rudkids-api/src/main/resources/application-local.yml
- rudkids-api/src/main/resources/db/prod/schema.sql
- rudkids-api/src/test/java/com/rudkids/api/admin/AdminControllerTest.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/item/ItemFixturesAndDocs.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/product/ProductFixturesAndDocs.java
- rudkids-api/src/test/java/com/rudkids/api/item/ItemControllerTest.java
- rudkids-core/src/main/java/com/rudkids/core/item/domain/ItemImage.java
- rudkids-core/src/main/java/com/rudkids/core/item/domain/itemOption/ItemOption.java
- rudkids-core/src/main/java/com/rudkids/core/item/domain/itemOptionGroup/ItemOptionGroup.java
- rudkids-core/src/main/java/com/rudkids/core/item/dto/ItemRequest.java
- rudkids-core/src/main/java/com/rudkids/core/item/dto/ItemResponse.java
- rudkids-core/src/main/java/com/rudkids/core/item/infrastructure/ItemFactoryImpl.java
- rudkids-core/src/main/java/com/rudkids/core/product/domain/ProductBannerImage.java
- rudkids-core/src/main/java/com/rudkids/core/product/dto/ProductRequest.java
- rudkids-core/src/main/java/com/rudkids/core/product/infrastructure/ProductFactoryImpl.java
- rudkids-core/src/main/java/com/rudkids/core/product/service/ProductServiceImpl.java
- rudkids-core/src/test/java/com/rudkids/core/cart/service/CartServiceTest.java
- rudkids-core/src/test/java/com/rudkids/core/common/fixtures/cart/CartServiceFixtures.java
- rudkids-core/src/test/java/com/rudkids/core/common/fixtures/item/ItemServiceFixtures.java
- rudkids-core/src/test/java/com/rudkids/core/common/fixtures/order/OrderServiceFixtures.java
- rudkids-core/src/test/java/com/rudkids/core/product/service/ProductServiceTest.java
> feat: ordering 추가 (#291)

- rudkids-api/src/main/java/com/rudkids/api/admin/AdminController.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/order/OrderFixturesAndDocs.java
- rudkids-core/src/main/java/com/rudkids/core/admin/dto/AdminRequest.java
- rudkids-core/src/main/java/com/rudkids/core/admin/service/AdminService.java
- rudkids-core/src/main/java/com/rudkids/core/admin/service/AdminServiceImpl.java
- rudkids-core/src/main/java/com/rudkids/core/config/FeignConfig.java
- rudkids-core/src/main/java/com/rudkids/core/delivery/domain/Address.java
- rudkids-core/src/main/java/com/rudkids/core/delivery/domain/Delivery.java
- rudkids-core/src/main/java/com/rudkids/core/order/domain/Order.java
- rudkids-core/src/main/java/com/rudkids/core/order/domain/OrderDelivery.java
- rudkids-core/src/main/java/com/rudkids/core/order/domain/OrderDeliveryStatus.java
- rudkids-core/src/main/java/com/rudkids/core/order/domain/OrderRepository.java
- rudkids-core/src/main/java/com/rudkids/core/order/dto/OrderResponse.java
- rudkids-core/src/main/java/com/rudkids/core/order/infrastructure/JpaOrderRepository.java
- rudkids-core/src/main/java/com/rudkids/core/order/infrastructure/OrderFactoryImpl.java
- rudkids-core/src/main/java/com/rudkids/core/order/infrastructure/OrderRepositoryImpl.java
- rudkids-core/src/main/java/com/rudkids/core/schedule/domain/DeliveryTrackState.java
- rudkids-core/src/main/java/com/rudkids/core/schedule/dto/DeliveryTrackResponse.java
- rudkids-core/src/main/java/com/rudkids/core/schedule/exception/DeliveryTrackingFailException.java
- rudkids-core/src/main/java/com/rudkids/core/schedule/infrastructure/DeliveryTracker.java
- rudkids-core/src/main/java/com/rudkids/core/schedule/service/Schedule.java
- rudkids-core/src/main/java/com/rudkids/core/verification/domain/VerificationCodeRepository.java
- rudkids-core/src/main/java/com/rudkids/core/verification/exception/NoSuchVerificationCodeException.java
- rudkids-core/src/main/java/com/rudkids/core/verification/infrastructure/VerifyCodeGenerator.java
- rudkids-core/src/test/java/com/rudkids/core/common/fixtures/order/OrderServiceFixtures.java
- rudkids-core/src/test/java/com/rudkids/core/order/service/OrderServiceTest.java
> fix: 배송상태 완료로 변경하는 스케쥴링 로직 구현 (#270)

- rudkids-api/src/main/resources/application-dev.yml
- rudkids-api/src/main/resources/application-prod.yml
- rudkids-api/src/main/resources/application.yml
- rudkids-api/src/main/resources/db/migration/V1__init.sql
- rudkids-api/src/main/resources/db/prod/data.sql
- rudkids-core/build.gradle
> feat: flyway 적용

- rudkids-api/build.gradle
- rudkids-api/src/docs/asciidoc/admin.adoc
- rudkids-api/src/docs/asciidoc/index.adoc
- rudkids-api/src/docs/asciidoc/mystery-product.adoc
- rudkids-api/src/main/java/com/rudkids/api/product/MysteryProductController.java
- rudkids-api/src/main/resources/application.yml
- rudkids-api/src/test/java/com/rudkids/api/admin/AdminControllerTest.java
- rudkids-api/src/test/java/com/rudkids/api/common/ControllerTest.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/admin/AdminFixturesAndDocs.java
- rudkids-api/src/test/java/com/rudkids/api/common/fixtures/product/MysteryProductFixturesAndDocs.java
- rudkids-api/src/test/java/com/rudkids/api/product/MysteryProductControllerTest.java
- rudkids-core/src/main/java/com/rudkids/core/admin/service/AdminService.java
- rudkids-core/src/main/java/com/rudkids/core/order/service/OrderService.java
> fix: 미스테리 docs 추가 (#335)
